ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - before: |
      export FLASK_APP=notblink
      export FLASK_ENV=development
    init: |
      pip install -e .
      flask init-db
    command: |
      flask run

vscode:
  extensions:
    - ms-python.python